openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
paths:
  /api/weather/{regionName}:
    get:
      tags:
        - weather-controller
      operationId: getTemperatureByRegionNameAndDate
      parameters:
        - name: regionName
          in: path
          required: true
          schema:
            type: string
        - name: dateTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: number
                format: double
    put:
      tags:
        - weather-controller
      operationId: updateRegionTemperature
      parameters:
        - name: regionName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRegionTemperatureDto'
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WeatherDto'
    post:
      tags:
        - weather-controller
      operationId: addNewRegion
      parameters:
        - name: regionName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Weather'
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WeatherDto'
    delete:
      tags:
        - weather-controller
      operationId: deleteRegion
      parameters:
        - name: regionName
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
  /weather_api/current/{location}:
    get:
      tags:
        - weather-api-controller
      operationId: getCurrentWeather
      parameters:
        - name: location
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WeatherApi'
components:
  schemas:
    UpdateRegionTemperatureDto:
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
    WeatherDto:
      type: object
      properties:
        regionId:
          type: string
          format: uuid
        regionName:
          type: string
        temperature:
          type: number
          format: double
        dateTime:
          type: string
          format: date-time
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
    Weather:
      type: object
      properties:
        regionId:
          type: string
          format: uuid
        regionName:
          type: string
        temperature:
          type: number
          format: double
        dateTime:
          type: string
          format: date-time
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
    Condition:
      type: object
      properties:
        text:
          type: string
    Current:
      type: object
      properties:
        last_updated:
          type: string
        temp_c:
          type: number
          format: double
        is_day:
          type: integer
          format: int32
        condition:
          $ref: '#/components/schemas/Condition'
        wind_kph:
          type: number
          format: double
        pressure_mb:
          type: number
          format: double
        precip_mm:
          type: number
          format: double
        humidity:
          type: integer
          format: int32
        cloud:
          type: integer
          format: int32
        feelslike_c:
          type: number
          format: double
        vis_km:
          type: number
          format: double
        gust_kph:
          type: number
          format: double
    Location:
      type: object
      properties:
        name:
          type: string
        region:
          type: string
        country:
          type: string
        tz_id:
          type: string
        localtime:
          type: string
    WeatherApi:
      type: object
      properties:
        location:
          $ref: '#/components/schemas/Location'
        current:
          $ref: '#/components/schemas/Current'
